// Generated by CoffeeScript 1.10.0
(function() {
  var resource;

  resource = function(options) {
    var controller, i, len, method, middleware, ref;
    if (options.controller != null) {
      controller = options.controller;
    } else {
      controller = require('./default-controller');
    }
    options.middleware = options.middleware || {};
    middleware = {};
    ref = ['all', 'get', 'update', 'create', 'destroy'];
    for (i = 0, len = ref.length; i < len; i++) {
      method = ref[i];
      if (options.middleware[method] != null) {
        middleware[method] = options.middleware[method];
      } else {
        middleware[method] = [];
      }
    }
    return function(req, res, next) {
      this.get('/', middleware.all, controller.all);
      this.get('/:id', middleware.get, controller.get);
      this.put('/:id', middleware.update, controller.update);
      this.post('/', middleware.create, controller.create);
      this["delete"]('/', middleware.destroy, controller.destroy);
      return next();
    };
  };

  module.exports = resource;

}).call(this);
