// Generated by CoffeeScript 1.10.0
(function() {
  var Router, dd, pluralize, resource;

  dd = require('dump-die');

  Router = require('express').Router;

  pluralize = require('pluralize');

  resource = function(Model, options) {
    var controller, i, len, method, middleware, pluralized, ref, router;
    router = new Router();
    if (options == null) {
      options = {};
    }
    if (options.controller != null) {
      controller = options.controller;
    } else {
      controller = require('./default-controller');
    }
    if (typeof controller === 'function') {
      controller = controller(Model);
    }
    options.middleware = options.middleware || {};
    middleware = {};
    ref = ['all', 'show', 'update', 'create', 'destroy'];
    for (i = 0, len = ref.length; i < len; i++) {
      method = ref[i];
      if (options.middleware[method] != null) {
        middleware[method] = options.middleware[method];
      } else {
        middleware[method] = [];
      }
    }
    pluralized = pluralize(Model.modelName);
    router.get("/" + pluralized + "/:id", middleware.show, controller.show);
    router.get("/" + pluralized + "/", middleware.all, controller.all);
    router.put("/" + pluralized + "/:id", middleware.update, controller.update);
    router.post("/" + pluralized + "/", middleware.create, controller.create);
    router["delete"]("/" + pluralized + "/", middleware.destroy, controller.destroy);
    return router;
  };

  module.exports = resource;

}).call(this);
