// Generated by CoffeeScript 1.10.0
(function() {
  var Router, pluralize, resource;

  Router = require('express').Router;

  pluralize = require('pluralize');

  resource = function(Model, options) {
    var controller, i, j, len, len1, method, middleware, only, pluralized, ref, ref1, router;
    router = new Router();
    if (options == null) {
      options = {};
    }
    if (options.controller != null) {
      controller = options.controller;
    } else {
      controller = require('./default-controller');
    }
    if (typeof controller === 'function') {
      controller = controller(Model);
    }
    options.middleware = options.middleware || {};
    middleware = {};
    ref = ['all', 'show', 'update', 'create', 'destroy'];
    for (i = 0, len = ref.length; i < len; i++) {
      method = ref[i];
      if (options.middleware[method] != null) {
        middleware[method] = options.middleware[method];
      } else {
        middleware[method] = [];
      }
    }
    pluralized = pluralize(Model.modelName);
    if (options.only == null) {
      options.only = ['show', 'all', 'create', 'update', 'delete'];
    }
    only = {};
    ref1 = options.only;
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      method = ref1[j];
      only[method] = true;
    }
    only.show && router.get("/" + pluralized + "/:id", middleware.show, controller.show);
    only.all && router.get("/" + pluralized + "/", middleware.all, controller.all);
    only.update && router.put("/" + pluralized + "/:id", middleware.update, controller.update);
    only.create && router.post("/" + pluralized + "/", middleware.create, controller.create);
    only.destroy && router["delete"]("/" + pluralized + "/", middleware.destroy, controller.destroy);
    return router;
  };

  module.exports = resource;

}).call(this);
