// Generated by CoffeeScript 1.10.0
(function() {
  var stripIllegalFields;

  stripIllegalFields = function(object) {
    var key, result, value;
    if (typeof object !== 'object') {
      return object;
    }
    result = {};
    for (key in object) {
      value = object[key];
      if (key !== '_id' && key !== '__v') {
        result[key] = stripIllegalFields(value);
      }
    }
    return result;
  };

  module.exports = stripIllegalFields;

}).call(this);
