// Generated by CoffeeScript 1.10.0
(function() {
  var stripIllegalFields;

  stripIllegalFields = function(object, currentDepth) {
    var key, result, value;
    if (currentDepth == null) {
      currentDepth = 0;
    }
    if (currentDepth > 200) {
      console.log(currentDepth, object);
      throw new Error('Recursive object can not be sent as json');
    }
    if (typeof object !== 'object') {
      return object;
    }
    result = {};
    for (key in object) {
      value = object[key];
      if (key !== '_id' && key !== '__v') {
        result[key] = stripIllegalFields(value, currentDepth + 1);
      }
    }
    return result;
  };

  module.exports = stripIllegalFields;

}).call(this);
